### ISSUE TITLE
Individual Meshes

### ISSUE THREAD

**Issue by TheNeikos** [StarArawn/bevy_tiled#14]
Currently, each chunk uses its own mesh. Could this be optimized? Depending on Orientation the mesh stays the same. Right now the position is also encoded in the mesh itself, this seems rather wasteful in terms of memory transfer+usage to me. 

Is there a way to reuse parts of this across chunks, and decouple the offset from the mesh itself? (Related to #3?)

**Comment by StarArawn** [comment]
Ideally we have a better way of specifying number of chunks and the size of the chunks. For really large maps or maps that are changed quite frequently I can see it being beneficial to chunk things up, but for smaller maps or maps that don't ever change having a single draw call/mesh would be much more ideal. As for positioning the only position that gets "encoded" in the mesh is the local position of each vertices. I don't see a way of improving the memory usage there.

**Comment by dmtaub** [comment]
The best way to do this would be leveraging the work put into bevy_tilemap. Issue here: https://github.com/StarArawn/bevy_tiled/issues/40
