### ISSUE TITLE
Map scaling introduces artifacts

### ISSUE THREAD

**Issue by martinlindhe** [StarArawn/bevy_tiled#47]
Running `cargo run --example ortho_main` and zooming out with Z, there is visible artifacts between tiles, as can be seen in attached video (Windows 10). Same issue is seen on macOS.

Using git master from today (bevy 0.5)

The issue starts to show in the video about 4 seconds in.

https://user-images.githubusercontent.com/181531/113852082-70e9e080-979c-11eb-916a-86ea451d484f.mp4

**Comment by dmtaub** [comment]
@martinlindhe I believe this is related to how the camera zooms relative to the meshes on which the tiles render.

 If you round the camera zoom to less problematic values, you should be able to reduce or eliminate this behavior.

**Comment by martinlindhe** [comment]
@dmtaub thanks, that could work too. I'll try to work something out

**Comment by StarArawn** [comment]
Make sure you set the texture atlas filter to nearest as well. Example:
```rust
  atlas_texture.sampler.min_filter = bevy::render::texture::FilterMode::Nearest;
```

**Comment by martinlindhe** [comment]
> 
> 
> Make sure you set the texture atlas filter to nearest as well. Example:
> 
> ```rust
>   atlas_texture.sampler.min_filter = bevy::render::texture::FilterMode::Nearest;
> ```

Thanks, but how would I go about accessing this, assuming we have some code that looks like https://github.com/StarArawn/bevy_tiled/blob/main/examples/ortho_main.rs

**Comment by dmtaub** [comment]
@martinlindhe example added to ortho_main

**Comment by martinlindhe** [comment]
I have been testing this for a bit now and something is still off. Using the example ortho_main, when launched the issue still remain randomly.
That is, on one launch the problem goes away, but in another launch the problem is back.
Closing the app and re-running `cargo run --example ortho_main` eventually leads to the problem going away. It seems to work correctly like 25% of the times.

Windows 10, Nvidia drivers.

**Comment by martinlindhe** [comment]
Just a speculation, but could the issue I see now be because the set_texture_filters_to_nearest() system maybe is run in nondeterministic order?

**Comment by dmtaub** [comment]
That seems likely...

**Comment by dmtaub** [comment]
@martinlindhe if you replace the line that adds the system with 
`.add_system_to_stage(PreUpdate, set_texture_filters_to_nearest.system())`
after adding `use bevy::app::CoreStage::PreUpdate;`
does it fix the issue for you?

**Comment by jmitchell89** [comment]
Ideally a better way to fix this issue is to have some `GameState` for loading. You have a system check to see if the texture has been loaded and if it has edit the texture to set the filtering to nearest. Then you just change your game state to playing or something.

**Comment by StarArawn** [comment]
Ideally a better way to fix this issue is to have some `GameState` for loading. You have a system check to see if the texture has been loaded and if it has edit the texture to set the filtering to nearest. Then you just change your game state to playing or something.

**Comment by dmtaub** [comment]
Indeed- that's exactly what we do in our game. We have a loading state where we listen for these objectReady events. My goal in adding this system is to demonstrate a quick and dirty way of achieving the same result. It looks like we'll have to demonstrate something about ordering as part of that, and for the purposes of that, I figure a PreUpdate system is ok, though we should comment that a better way is to use a GameState resource.

**Comment by martinlindhe** [comment]
> 
> 
> That seems likely....
> 
> @martinlindhe if you replace the line that adds the system with
> `.add_system_to_stage(PreUpdate, set_texture_filters_to_nearest.system())`
> after adding `use bevy::app::CoreStage::PreUpdate;`
> does it fix the issue for you?

Yes! This now works 100%, thank you very much :)
