### ISSUE TITLE
wasm builds fail on get_root_path

### ISSUE THREAD

**Issue by rparrett** [StarArawn/bevy_tiled#54]
Since eb124a30babf3b42ea9ad107653aee0570c678b6

```
error[E0599]: no function or associated item named `get_root_path` found for struct `WasmAssetIo` in the current scope
  --> /Users/robparrett/.cargo/git/checkouts/bevy_tiled-85a429c236b45725/d997e92/src/map.rs:61:44
   |
61 |         let root_dir = asset::WasmAssetIo::get_root_path();
   |                                            ^^^^^^^^^^^^^ function or associated item not found in `WasmAssetIo`
```

Things are generally working very well prior to this commit.

**Comment by rparrett** [comment]
It seems that `AndroidAssetIo` also does not have `get_root_path`.

**Comment by dmtaub** [comment]
Oof. OK - any ideas what we can do there? 
Thanks for trying it out - I don't build for Wasm right now, so I was hoping someone who does would test this.
Perhaps I should revert for now...

**Comment by rparrett** [comment]
I'm not sure. I might be able to test more later tonight.

Is `create_platform_default_asset_io()` (and `.path` on the resulting AssetIo`) something that would help?

**Comment by rparrett** [comment]
This may be of interest to @SarthakSingh31 @f-hanzlik
