### ISSUE TITLE
Adding some light documentation

### ISSUE THREAD

**Issue by will-sloan** [StarArawn/bevy_tiled#8]
I was trying to get through some of the code on how the map was processed and loaded, like in functions TiledMapLoader and process_loaded_tile_maps, but the code is a little dense and sparsely documented. I'd like to help contribute to this project, and having a little bit more info on how the main processes worked would be a great help.

**Comment by dmtaub** [comment]
There is now a readme, and I tried to add comments in the code (check out `bevy-0.4-objects` branch) but if there are particular things you want to know more about, please let me know
